version: '2'
services:
  tracker-server:
    image: nginx-fastdfs:lz
    #    network_mode: "host"
    networks:
      mynet1:
        ipv4_address: 172.19.0.3
    command: "./tracker.sh"

  storage-server:
    image: nginx-fastdfs:lz
    volumes:
      - "./docker/storage_base_path:/data/fast_data"
    environment:
      TRACKER_SERVER: "172.19.0.3:22122"
      GROUP_NAME: "M00"
      TRACKER_IP: "172.19.0.3:22122"
      #    network_mode: "host"
    networks:
      mynet1:
        ipv4_address: 172.19.0.2
    command: "./storage.sh"
# 创建网络，以固定容器创建时的ip地址
networks:
  mynet1:
    ipam:
      config:
        - subnet: 172.19.0.0/16
  ~